ignore_path_regex:
  - .*(doc).*
  - .*(examples).*
  - .*(versioneer).*

include_path_regex:
  - .*(skxray).*

test_regex:
  - .*(test).*

blacklist_packages:
  - setupext
  - versioneer
  - ctrans
  - skxray
  - src
  - netCDF4
  - pyFAI