ignore_path_regex:
  - .*(doc).*
  - .*(examples).*
  - .*(versioneer).*

include_path_regex:
  - .*(metadatastore).*

test_regex:
  - .*(test).*

blacklist_packages:
  - setupext
  - versioneer
  - ctrans