language: python
sudo: false

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: nightly
  allow_failures:
    - python: nightly
    # because I am indifferent about py2k support
    - python: 2.6
    - python: 2.7

before_install:
  # - wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION pytest jinja2 pyyaml
  - source activate testenv
  - pip install codecov pytest-cov
  - pip install https://github.com/ericdill/depfinder/zipball/master#egg=depfinder
  - pip install https://github.com/ericdill/whatsmyversion/zipball/master#egg=whatsmyversion
  - python setup.py install

script:
  - ./test

after_success:
  - codecov
